### ISSUE TITLE
CocoaScript Support

### ISSUE THREAD

**Issue by bomberstudios** [makzan/Sketch-Plugin-Scripts#1]
Good Morning / Afternoon / Night (depending on your timezone :)!

As you probably know, Sketch will switch its scripting backend from JSTalk to CocoaScript in the upcoming version 3.0.2.

As a result of this change, **some plugins will stop working unless you fix them**.

Guess what? **Yours seems to be one of them**. But worry not! We've identified some of the issues, and the fixes are easy to do (so far :)

Please take a look at the info we've compiled at https://github.com/sketchplugins/cocoascript-migration/, make your changes, and test your scripts with [the latest beta](http://bohemiancoding.com/sketch/beta/). Please don't hesitate to get in touch if you need more help!

Sorry about the extra work, and thank you for your contribution to the amazing Sketch Plugins community :)

Ale M — Bohemian Coding

**Comment by makzan** [comment]
Thanks @bomberstudios for raising this update issue. I'll definitely work on the migration. It should be done within this week.

**Comment by makzan** [comment]
Compatibility issue is fixed in b02681b6580946a2fd95d433e87c498dc25059d1 commit.
